### ISSUE TITLE
Add ticks and colors to the graph

### ISSUE THREAD

**Issue by moshfeu** [spread-the-code/github-stats#5]
Currently there are no ticks on the graph so the user has to hover a column to start evaluating the numbers. Ticks can help with that.

![Screen Shot 2020-07-02 at 14 22 44](https://user-images.githubusercontent.com/3723951/86353171-84957300-bc6f-11ea-9d38-f962cc355a7c.png)

Also, make the columns in a different colors could be nice.

**Comment by shayanypn** [comment]
will handle here https://github.com/spread-the-code/github-stats/pull/9

**Comment by shayanypn** [comment]
Resolved on https://github.com/spread-the-code/github-stats/pull/9
